server :
  port : 9090
  servlet:
   context-path: /IES

ies : 
  application :
    message : Welcome to Spring Boot IES Application-dev
    name : IES-App
    cw_reg_success: Case Worker Registered Successfully....!!
    cw_reg_failure: Case Worker Registration Failed....!!

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: ies_app
    password: ies_app
  jpa:
    properties:      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        ddl-auto: update      
        